const express = require('express');
const membersRouter = express.Router();
const { membersController } = require('../controllers/membersController');
const { verifyToken } = require('../controllers/authController');

membersRouter.get('/getUserData/:type/:id', verifyToken, membersController.getUserData);
membersRouter.get('/getCompanyData/:type/:id', verifyToken, membersController.getCompanyData);
membersRouter.get('/getMemberActivity/:type/:id', verifyToken, membersController.getMemberActivity);
membersRouter.get('/getUserExperience/:id', verifyToken, membersController.getUserExperience);
membersRouter.get('/getUserEducation/:id', verifyToken, membersController.getUserEducation);
membersRouter.get('/getUserSkills/:id', verifyToken, membersController.getUserSkills);
membersRouter.put('/updateUserIntro/:userid', verifyToken, membersController.updateUserIntro);
membersRouter.put('/updateUserAbout/:userid', verifyToken, membersController.updateUserAbout);
membersRouter.put('/updateCompanyAbout/:companyid', verifyToken, membersController.updateCompanyAbout);
membersRouter.post('/newExperience/:userid', verifyToken, membersController.newExperience);
membersRouter.put('/editExperience/:userid/:expid', verifyToken, membersController.editExperience);
membersRouter.delete('/deleteExperience/:expid', verifyToken, membersController.deleteExperience);
membersRouter.post('/newEducation/:userId', verifyToken, membersController.newEducation);
membersRouter.put('/editEducation/:userid/:educationid', verifyToken, membersController.editEducation);
membersRouter.delete('/deleteEducation/:educationid', verifyToken, membersController.deleteEducation);
membersRouter.post('/newSkill/:userid', verifyToken, membersController.newSkill);
membersRouter.delete('/deleteSkill/:skillid', verifyToken, membersController.deleteSkill);
membersRouter.get('/getCompanyJobOpenings/:id', verifyToken, membersController.getCompanyJobOpenings);
membersRouter.put('/updateCompanyIntro/:id', verifyToken, membersController.updateCompanyIntro);
membersRouter.put('/changeJobStatus/:id', verifyToken, membersController.changeJobStatus);
membersRouter.post('/follow/:userid/:receiverid', verifyToken, membersController.follow);
membersRouter.get('/checkFollow/:userid/:memberid/:usertype/:membertype', verifyToken, membersController.checkFollow);
membersRouter.post('/unfollow/:userid/:receiverid', verifyToken, membersController.unfollow);
membersRouter.post('/connect/:userid/:receiverid', verifyToken, membersController.connect);
membersRouter.get('/getUserConnections/:userid', verifyToken, membersController.getUserConnections);
membersRouter.delete('/removeConnection/:userid/:connectionid', verifyToken, membersController.removeConnection);
membersRouter.get('/getAllUsers/:userid', verifyToken, membersController.getAllUsers);
membersRouter.get('/getRequests/:userid', verifyToken, membersController.getRequests);
membersRouter.post('/handleConnectionReq/:reqid/:status', verifyToken, membersController.handleConnectionReq)
module.exports = { membersRouter };
